name: 'fintech_analytics'
version: '1.0.0'
profile: 'fintech_analytics'
require-dbt-version: [">=1.10.0", "<2.0.0"]

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  fintech_analytics:
    +schema: raw
    raw_customers:
      +column_types:
        signup_date: varchar(10)
        date_of_birth: varchar(10)
    raw_accounts:
      +column_types:
        opened_date: varchar(10)
        closed_date: varchar(10)
    raw_transactions:
      +column_types:
        transaction_date: varchar(10)

models:
  fintech_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts
      core:
        +schema: marts_core
      finance:
        +schema: marts_finance